version: '3.7'

services:
  mysql:
    image: mysql:8.0
    restart: always
    container_name: mysql-yugod
    environment:
      MYSQL_ROOT_PASSWORD: ysy123
      MYSQL_DATABASE: yugod_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
