/*
 * gin-api
 *
 * gin-api
 *
 * API version: openapi.v3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
)

type UserAPI struct {
}

// Post /api/user/create
func (api *UserAPI) CreateUser(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

