/*
 * gin-api
 *
 * gin-api
 *
 * API version: openapi.v3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// CommonResponse - 
type CommonResponse struct {

	// 
	Message string `json:"message"`

	Status ResponseStatus `json:"status"`
}
