/*
 * gin-api
 *
 * gin-api
 *
 * API version: openapi.v3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ResponseStatus : 
type ResponseStatus string

// List of ResponseStatus
const (
	RESPONSESTATUS_SUCCESS ResponseStatus = "success"
	RESPONSESTATUS_FAIL ResponseStatus = "fail"
	RESPONSESTATUS_ERROR ResponseStatus = "error"
)
