/*
 * gin-api
 *
 * gin-api
 *
 * API version: openapi.v3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// GetMdbyPathResponse - 
type GetMdbyPathResponse struct {

	// 
	Message string `json:"message"`

	Status ResponseStatus `json:"status"`

	// 
	Data string `json:"data"`
}
