/*
 * gin-api
 *
 * gin-api
 *
 * API version: openapi.v3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// GetUserInfoResponse - 
type GetUserInfoResponse struct {

	// 
	Message string `json:"message"`

	Status ResponseStatus `json:"status"`

	Data GetUserInfoData `json:"data"`
}
