/*
 * gin-api
 *
 * gin-api
 *
 * API version: openapi.v3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// CreateUserParam - 创建真实的用户所需的参数
type CreateUserParam struct {

	// 账号
	UserName string `json:"userName"`

	// 昵称
	Name string `json:"name"`

	// 密码
	Password string `json:"password"`

	// 身份：1,游客;2,用户;
	Auth int32 `json:"auth"`

	// 邮箱
	Email string `json:"email,omitempty"`

	// 年龄
	Age int32 `json:"age,omitempty"`
}
