/*
 * gin-api
 *
 * gin-api
 *
 * API version: openapi.v3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// GetUserInfoData - 
type GetUserInfoData struct {

	// 
	UserId int32 `json:"userId"`

	// 
	UserName string `json:"user_name"`

	// 
	Email string `json:"email,omitempty"`

	// 
	Auth int32 `json:"auth"`

	// 
	Age int32 `json:"age,omitempty"`

	// 昵称
	Name string `json:"name"`
}
