/*
 * gin-api
 *
 * gin-api
 *
 * API version: openapi.v3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// SetClickVolumeByTagParam - 
type SetClickVolumeByTagParam struct {

	// 
	Tag string `json:"tag"`
}
