/*
 * gin-api
 *
 * gin-api
 *
 * API version: openapi.v3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// GetClickVolumeData - 
type GetClickVolumeData struct {

	// 网站总点击量
	Web int32 `json:"web"`

	// 笔记点击量
	Note int32 `json:"note"`
}
